apiVersion: apps/v1
kind: Deployment
metadata:
  name: blockchain-server
spec:
  selector:
    matchLabels:
      app: blockchain-server
  template:
    metadata:
      labels:
        app: blockchain-server
    spec:
      containers:
      - name: blockchain-server
        image: <YOUR_IMAGE_GOES_HERE>
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
